# Generated by Django 5.1.6 on 2025-02-28 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=100)),
                ('date_of_analysis', models.DateField(auto_now_add=True)),
                ('moisture', models.FloatField()),
                ('ash', models.FloatField()),
                ('crude_protein', models.FloatField()),
                ('crude_fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('carbohydrates', models.FloatField(blank=True, null=True)),
                ('gross_energy', models.FloatField()),
                ('vitamin_a', models.FloatField()),
                ('vitamin_c', models.FloatField()),
                ('ai_analysis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
